languageCode = "en-us"
title = "My New Hugo Site"
theme = "mytheme"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[module]
[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "content/images"
  target = "assets/images"

[[module.mounts]]
  source = "content/v1.0/images"
  target = "assets/v1.0/images"

[[module.mounts]]
  source = "content/v1.5/images"
  target = "assets/v1.5/images"

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "data"
  target = "data"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "archetypes"
  target = "archetypes"
